Hешение задачи 1.1.4
oneskillonesoft2/maximdemidoff pull request #2
Opened 2024-01-19 07:50 UTC by oneskillonesoft

2024-01-19 12:33 UTC, pdasilem requested changes

2024-01-19 12:33 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        } catch (Exception e) {
роллбэк транзакции в случае ошибки

2024-01-19 12:33 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        String sql = "DROP TABLE IF EXISTS Users";
как этот метод работает?

2024-01-19 12:33 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        }catch (QueryException e) {
роллбэк транзакции?
и исключение - лучше хибер

2024-01-19 21:53 UTC, oneskillonesoft commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        String sql = "DROP TABLE IF EXISTS Users";
А что не так с ним? Вроде валидный запрос.

2024-01-20 14:52 UTC, pdasilem requested changes

2024-01-20 14:52 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        String sql = "DROP TABLE IF EXISTS Users";
в пр не видно было остальные строчки

2024-01-20 14:52 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +            transaction = session.beginTransaction();
когда тебе нужен объект транзакции?

2024-01-20 14:52 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +//package jm.task.core.jdbc.dao;
раскомментировать весь класс

2024-01-20 14:52 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/Util.java
> -        Connection conn = null;
почему удалил? 
нужны обе реализации

2024-01-20 17:20 UTC, oneskillonesoft commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +        String sql = "DROP TABLE IF EXISTS Users";
Все, я понял вопрос, ну да, я исправил этот момент

2024-01-20 17:28 UTC, oneskillonesoft commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +            transaction = session.beginTransaction();
В данном контексте использование транзакции (Transaction) является излишним для операций чтения, таких как получение данных. Основная цель транзакции — обеспечить целостность данных при операциях модификации (например, вставка, обновление, удаление). Для операций чтения, как правило, достаточно просто открыть сессию и выполнить запрос.

2024-01-20 17:29 UTC, oneskillonesoft commented on src/main/java/jm/task/core/jdbc/dao/UserDaoHibernateImpl.java
> +            transaction = session.beginTransaction();
Теперь буду знать)

2024-01-20 20:02 UTC, oneskillonesoft commented on src/main/java/jm/task/core/jdbc/util/Util.java
> -        Connection conn = null;
Сделал

2024-01-20 20:02 UTC, oneskillonesoft commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +//package jm.task.core.jdbc.dao;
Сделал

2024-01-20 20:22 UTC, pdasilem approved these changes

2024-01-20 23:19 UTC, merged